### ISSUE TITLE
Offset

### ISSUE THREAD

**Issue by Kuartzz** [ObjectiveSlayer/ComfyGray#1]
![image](https://user-images.githubusercontent.com/107305901/173185866-b18ca44d-e5b5-4ced-98ab-285d7e217f57.png)
The user name is not supposed to be like that i guess

![image](https://user-images.githubusercontent.com/107305901/173185872-31118d42-97bb-4eee-b835-551435e6e3b9.png)
If that could be rounded, it could be cleaner.

**Comment by ObjectiveSlayer** [comment]
Apologies for the very late reply, I've never seen this issue before. The first bug was fixed a long time ago. And the second one isn't a bug, It's rounded but you have to scroll down.
