### ISSUE TITLE
User profile looks broken, blank space where profile picture is normally.

### ISSUE THREAD

**Issue by Blisterexe** [ObjectiveSlayer/ComfyGray#13]
i am using vencord, here is a picture of the issue
![image](https://user-images.githubusercontent.com/128065612/236702144-62b2672a-8397-4c04-b96c-81f8009f0c31.png)

**Comment by sssrankedghoul** [comment]
https://github.com/ObjectiveSlayer/ComfyGray/pull/14

**Comment by Blisterexe** [comment]
ah, i see, sorry for the bother.
