### ISSUE TITLE
New light profiles are unreadable

### ISSUE THREAD

**Issue by moon-dew** [ObjectiveSlayer/ComfyGray#8]
<img width="230" alt="Screen Shot 2022-11-13 at 1 15 04 AM" src="https://user-images.githubusercontent.com/58519807/201514539-59a06d79-29d3-49fa-a80c-eb36d4e641b0.png">

I think this says everything lol if you need any additional information please let me know, not sure if this feature is rolled out to general deploy or just public test build? Anyway thanks so much for making this theme, it's my favorite for better discord so far!

**Comment by ObjectiveSlayer** [comment]
Oh hey, Really sorry for the late reply... You can try to enable the "Sync profile themes" option in Settings>Accessibility, let me know if that works.
